# VIA無効化でフラッシュ約3KB削減（容量超過対策）
COMBO_ENABLE = yes
VIA_ENABLE = no
MOUSEKEY_ENABLE = yes
RGBLIGHT_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAFLAGS += -flto
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = no
OLED_ENABLE = yes
